print ("\t\tMoklet Express")
print ("\t\t\t\tTelkom School\n\t\t\t\tJl Danau Ranau, Sawojajar\n\t\t\t\tKota Malang\n\t\t\t\tTelepon: 081223488999")
data_pengirim=input ("Masukan nama pengirim: ")
data_asal=input ("Masukan kota asal: ")
data_alamat_pengirim=input ("Masukan alamat pengirim: ")
data_penerima=input ("\nMasukan nama penerima: ")
data_telepon=input ("Masukan nomor telepon penerima: ")
data_tujuan=input ("Masukan kota tujuan: ")
data_alamat_penerima=input ("Masukan alamat penerima: ")
data_pos=input ("Masukan kode pos: ")
data_intruksi=input ("\nMasukan intruksi khusus: ")
data_nilai=input ("Masukan nilai barang: ")
data_keterangan=input ("Masukan keterangan barang: ")
print ("\nPengirim:")
print (data_pengirim)
print (data_alamat_pengirim)
print ("\n\nKota",data_asal)
print ("\t\t\t\tKode pos:",data_pos)
print ("Indonesia\t\t\tTelepon:",data_telepon,)
print ("attn: ")
print ("Penerima:",data_penerima)
print (data_alamat_penerima)
print ("Kota",data_tujuan)
print ("\nattn: ")
print ("Intruksi Khusus: ",data_intruksi)
print ("Nilai Barang: ",data_nilai)
print ("Keterangan Barang: ",data_keterangan)
print ("\t\t\tResi ini di cetak secara otomatis dengan Moklet express\n\t\t\tuntuk pengecekan status kiriman silahkan mengunjungi www.moklet.co.id")

